Assignment Questions:
1. Create 1d, 2d, 3d Arrays
2. Create 7X7 Random Integer & Random Float Arrays
3. Create Identity Matrix with square value of 10 (np.eye() & np.identity())
4. create 10 elements 1d array with 3 elements of np.nan, eliminate the nan array and display both the arrays
5. create full array (3,3) with filled value of 10 & multiply same array with (3,3) Random Integer array

In [4]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
np.random.randint(1,11,size=(7,7))

array([[ 1,  4,  6,  1,  2, 10,  1],
       [ 5,  2,  3,  2, 10,  3,  8],
       [ 9,  9,  7,  8,  2, 10,  3],
       [ 5, 10,  5, 10,  4,  6, 10],
       [10, 10,  6,  7,  9,  6,  3],
       [ 7,  5,  7,  9,  4, 10,  3],
       [ 6,  9,  1,  6,  1,  3,  2]])

In [15]:
np.random.rand(7,7)

array([[0.20509512, 0.32450693, 0.7072332 , 0.64055614, 0.92795893,
        0.07945921, 0.90978795],
       [0.16049721, 0.43915378, 0.88688808, 0.01697763, 0.10789596,
        0.84472599, 0.95271186],
       [0.20227241, 0.57814967, 0.74755167, 0.49798491, 0.70949272,
        0.36691707, 0.85120964],
       [0.05740359, 0.91159632, 0.29183454, 0.21779108, 0.22423775,
        0.76424856, 0.22964705],
       [0.61806324, 0.07172286, 0.07491454, 0.71764434, 0.4111571 ,
        0.20164432, 0.19135435],
       [0.93336524, 0.91838423, 0.70770173, 0.17114502, 0.0905136 ,
        0.5171934 , 0.02264113],
       [0.26879815, 0.99509802, 0.9106546 , 0.86599633, 0.74438271,
        0.09882565, 0.13151593]])

In [20]:
np.identity(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [28]:
a=np.array([1,2,3,np.nan,np.nan,np.nan,7,8,9,10])
print(a)
b=a[~ np.isnan(a)]
print(b)

[ 1.  2.  3. nan nan nan  7.  8.  9. 10.]
[ 1.  2.  3.  7.  8.  9. 10.]


In [34]:
a1=np.ones((3,3),dtype=int)*10
a1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [36]:
b1=np.random.randint(1,6,size=(3,3))
b1

array([[1, 3, 4],
       [1, 3, 2],
       [3, 5, 2]])

In [37]:
mul=a1*b1
mul

array([[10, 30, 40],
       [10, 30, 20],
       [30, 50, 20]])

# HW1:Slicing Indexes

In [40]:
slicing=np.array([1,2,3,4,5,6,7,8,9,10])
slicing[:5:1]

array([1, 2, 3, 4, 5])

In [41]:
slicing[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
slicing[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slicing[-5:-2]

array([6, 7, 8])

In [47]:
slicing[:-9]

array([1])

# HW:Numpy Operations

In [48]:
operations=np.array([10,20,30,40,50])
np.argmax(operations)

4

In [54]:
a2= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b2 = a2.reshape(3,3)
b2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a3= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b3 = np.floor(a3)
b3

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
a4=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b4=np.sin(a4)
b4

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [59]:
a5=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b5=np.cos(a5)
b5

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])