# Dailt Tasks Day1

In [9]:
import numpy as np

In [5]:
distance = [10,20,30,40]
time = [.10,.20,.30,.40]


In [10]:
np.distance=np.array([10,20,30,40])
np.time=np.array([.10,.20,.30,.40])
print("Speed = ")
np.distance/np.time

Speed = 


array([100., 100., 100., 100.])

In [15]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[10,20,30],[40,50,60],[70,80,90]])
matrix3=matrix1+matrix2
print(matrix3)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [20]:
array1=np.array([1,2,3,4,5],dtype='int')
print(array1)

array([1, 2, 3, 4, 5])

In [21]:
def add_5_values(a,b,c,d,e):
    result=a+b+c+d+e
    print(result)

In [22]:
add_5_values(10,20,30,40,50)

150


In [56]:
np.array([[[0,1], [3,4], [6,7]], [[9,10],[12,13],[15,16]], [[18,19],[21,22], [24,25]]]).ndim

3

In [47]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [48]:
a2=np.array([4,5,6])
a2

array([4, 5, 6])

In [39]:
a3=np.array([[1,2,3],[4,5,6]])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a4=np.array([[7,8,9],[10,11,12]])
a4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
a5=np.array([[[0,1,2], [3,4,5], [6,7,8]]])
a5

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [63]:
a6=np.array([[[9,10,11],[12,13,14],[15,16,17]]])
a6

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [49]:
a_Add=a1+a2
a_Add

array([5, 7, 9])

In [50]:
a_sub=a3-a4
a_sub

array([[-6, -6, -6],
       [-6, -6, -6]])

In [60]:
a_mul=a5*a6
a_mul

array([[[  0,  10,  22],
        [ 36,  52,  70],
        [ 90, 112, 136]]])

In [68]:
s1=np.ones((3,3,3),dtype=int)
s2=np.ones((3,3,3),dtype=int)
s3=s1+s2
s3

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [69]:
array1=np.array([[3,5,7,9,11,13,15],[17,19,21,23,25,27,29]])
array1

array([[ 3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29]])

In [71]:
array2=np.ones((2,7),dtype=int)
array2

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [72]:
array_add=array1+array2
array_add

array([[ 4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30]])

In [74]:
np.random.rand(3,3)

array([[0.92869316, 0.2769036 , 0.12412815],
       [0.13337804, 0.72569854, 0.24520717],
       [0.14345169, 0.69231435, 0.28954369]])

In [76]:
np.random.randint(1,3, size=(2,2))

array([[1, 2],
       [2, 2]])

In [78]:
r1=np.random.randint(1,6, size=(5,5))
r1

array([[4, 5, 1, 2, 3],
       [3, 1, 2, 2, 5],
       [2, 4, 1, 5, 4],
       [4, 4, 4, 4, 1],
       [2, 2, 1, 4, 4]])

In [80]:
r2=np.identity(5,dtype=int)
r2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [81]:
r3=r1*r2
r3

array([[4, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

In [89]:
r4=np.full((3,3),10)
r4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [91]:
r5=np.random.randint(1,6,size=(3,3))
r5

array([[3, 5, 5],
       [3, 5, 3],
       [1, 1, 4]])

In [93]:
r6=r4*r5


array([[30, 50, 50],
       [30, 50, 30],
       [10, 10, 40]])

Task    . 
1.Count the number of times each value appears in an array of integers
2.Create a Numpy array [[0,1,2],[3,4,5],[6,7,8],[9,10,11]] and filter the elements greter than 5
3.Create a Numpy array having Nan (Not a Number)and Print it, also print same array omitting all elements which are Nan
EX: np.array([np.nan, 1,2,np.nan,3,4,5])
4.Create 10X10 array with Random Integer Values and filter the elements greter than 10


In [14]:
t1=np.array([1,2,3,4])
t2=np.count_nonzero(t1==2)
t2

1

In [98]:
n1=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
n2=np.array(n1>5)
print(n2)
n2=n1[n1>5]
n2

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


array([ 6,  7,  8,  9, 10, 11])

In [12]:
nan=np.array([np.nan,10,20,np.nan,30,40,50])
print(nan)
nan[~ np.isnan(nan)]

[nan 10. 20. nan 30. 40. 50.]


array([10., 20., 30., 40., 50.])

In [114]:
a=np.random.randint(1,20,size=(10,10))
b=np.array(a>10)
print(b)
a[a>10]

[[False False  True False False  True False False False  True]
 [ True False False False False False  True  True False False]
 [False  True False False False False  True  True False False]
 [False False False False  True  True False False False  True]
 [False False False  True  True  True False False  True  True]
 [ True  True False False  True False False False  True  True]
 [ True  True  True False False False False False False  True]
 [False  True False  True False False  True  True  True False]
 [False False False False False False False False False  True]
 [False False False  True  True False False  True  True False]]


array([15, 11, 13, 19, 11, 18, 12, 12, 14, 12, 15, 19, 19, 15, 11, 12, 17,
       12, 13, 16, 13, 12, 15, 12, 14, 16, 14, 16, 12, 13, 14, 11, 14, 17,
       15, 11])