In [2]:
import numpy as np

In [7]:
a=np.array([1,2,3,4,5,6])

In [8]:
a[0],a[1]

(1, 2)

In [14]:
a[0::]

array([1, 2, 3, 4, 5, 6])

In [15]:
a[[0,-2,4]]
#this will create another numpy array

array([1, 5, 5])

In [16]:
#this will justr create another lists
a[1],a[-2]

(2, 5)

# Array Types

In [17]:
a.dtype

dtype('int32')

In [19]:
#changing the array datatype
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

# Dimensions

In [22]:
#creating multi dimensions
b=np.array([[1,2,3],[1,2,3]])

In [23]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [24]:
b.shape

(2, 3)

In [26]:
#dimesion of the array
b.ndim

2

In [27]:
b.size

6

In [28]:
# dimesion should match
c= np.array([
            [
              [1,2,3],
              [1,2,3]
             ],
             
             [1,2,3]
            ])

C:\Users\sriku\AppData\Local\Temp/ipykernel_5560/2741004381.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c= np.array([


In [30]:
c.dtype

dtype('O')

In [32]:
c.shape
#this is wrong

(2,)

# Indexing in matrix

In [33]:
A=np.array([[1,2,3]#1
           ,[1,2,3]#2
           ,[1,2,3]])#3

In [35]:
A[1]

array([1, 2, 3])

In [37]:
#select row first and then select the column index
A[1][0]

1

In [39]:
#another method to index
A[1,0]

1

In [40]:
#Slicing
A[0:2]
#this chosses the rows

array([[1, 2, 3],
       [1, 2, 3]])

In [42]:
A[:,:2]
#choosing columns(this ',' represents the row)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [45]:
#choosing both row and colmuns
A[:2,:2]

array([[1, 2],
       [1, 2]])

In [46]:
#modifying values in the array
A[2] = 10

In [48]:
A
#changed the value in row with index 2 to 10

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [10, 10, 10]])

# Statistics

In [49]:
a=np.array([1,2,3,4])

In [50]:
a.mean()

2.5

In [51]:
a.std()

1.118033988749895

In [53]:
a.sum()

10

In [54]:
a.var()

1.25

# VECTOR OPERATIONS

In [5]:
a=np.arange(4)

In [6]:
a

array([0, 1, 2, 3])

In [7]:
a+10

array([10, 11, 12, 13])

In [8]:
a*10

array([ 0, 10, 20, 30])

In [9]:
a

array([0, 1, 2, 3])

In [10]:
a=a+100

In [11]:
a

array([100, 101, 102, 103])

In [12]:
l=[0,1,2,3]

In [14]:
[i*10 for i in l]

[0, 10, 20, 30]

In [15]:
b=np.array([1,2,3,4])

In [16]:
a+b

array([101, 103, 105, 107])

In [17]:
a*b

array([100, 202, 306, 412])

# Boolean in Numpy

In [3]:
a=np.arange(5)

In [4]:
a[0],a[4]

(0, 4)

In [6]:
a[[1,-3]]

array([1, 2])

In [7]:
a[[True,False,True,False,True]]

array([0, 2, 4])

In [8]:
a>=2

array([False, False,  True,  True,  True])

In [9]:
a[a>=2]

array([2, 3, 4])

In [10]:
a.mean()

2.0

In [13]:
a[(a ==0)|(a ==6)]

array([0])

# Certifications

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a.var()

1.25

In [6]:
a.max()

4

In [7]:
a.std()

1.118033988749895

In [9]:
np.mean(a,axis=0)

2.5

In [10]:
a.mean()

2.5

In [20]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [21]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
a.mean()

4.0

In [23]:
np.mean(a,axis=0)

array([3., 4., 5.])

In [24]:
np.mean(a,axis=1)

array([1., 4., 7.])

In [ ]:
np.va